<a href="https://colab.research.google.com/github/R0berth456/-Tarea09-EjerciciosUnidad04AB_Eliminaci-nGaussianaVsGaussJordan/blob/main/%5BTarea09%5D_EjerciciosUnidad04AB_Eliminaci%C3%B3nGaussianaVsGaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Segundo Literal

a)
–X1 + 4X2 + X3 = 8\
    5/3X1 + 2/3X2 + 2/3X3 = 1\
   2X1 + X2 + 4X3 = 11


In [2]:
import numpy as np
A = [
    [-1, 4, 1],
    [round(5/3, 2), round(2/3, 2), round(2/3, 2)],
    [2, 1, 4]
]

b = [8, 1, 11]

x = np.linalg.solve(A, b)
x

array([-1.00651042,  0.99739583,  3.00390625])

b) 4X1 + 2X2 – X3 = -5\
    1/9X1 + 1/9X2 – 1/3X3 = -1\
      X1 + 4X2 + 2X3 = 9


In [3]:
import numpy as np

A = [
    [4, 2, -1],
    [round(1/9, 2), round(1/9, 2), round(1/3, 2)],
    [1, 4, 2]
]

b = [-5, -1, 9]

x = np.linalg.solve(A, b)
x

array([-4.52993348,  4.97117517, -3.17738359])

Tercer Literal

In [4]:
#Algoritmo utilizado
import numpy as np
def eliminacion_gaussiana(A: np.ndarray) -> np.ndarray:
    A = np.array(A)
    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    for i in range(0, n - 1):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            print(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]


    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # --- Sustitución hacia atrás
    solucion = np.zeros(n)
    solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = (A[i, n] - suma) / A[i, i]

    return solucion

a) X1 – X2 + 3X3 = 2\
    3X1 – 3X2 + X3 = -1\
     X1 + X2 = 3


In [5]:
A = [[1, -1, 3, 2], [3, -3, 1, -1], [1, 1, 0, 3]]
x = eliminacion_gaussiana(A)
x

Intercambiando filas 1 y 2


array([1.1875, 1.8125, 0.875 ])

b) 2X1 – 1.5X2 + 3X3 = 1\
-X1 + 2X3 = 3\
4X1 – 4.5X2 + 5X3 = 1


In [6]:
A = [[2, -1.5, 3, 1], [-1, 0, 2, 3], [4, -4.5, 5, 1]]
x = eliminacion_gaussiana(A)
x


Intercambiando filas 0 y 1


array([-1., -0.,  1.])

c) 2X1 = 3\
X1 + 1.5X2 = 4.5\
-3X2 + 0.5X3 = -6.6\
2X1 – 2X2 + X3 + X4 = 0.8


In [7]:
A = [[2, 0, 0, 0, 3], [1, 1.5, 0, 0, 4.5], [0, -3, 0.5, 0, -6.6], [2, -2, 1, 1, 0.8]]
x = eliminacion_gaussiana(A)
x


Intercambiando filas 0 y 1


array([ 1.5,  2. , -1.2,  3. ])

d) X1 + X2 + X4 = 2\
2X1 + X2 – X3 +X4 = 1\
4X1 – X2 – 2X3 + 2X4 = 0\
3X1 – X2 – X3 + 2X4 = -3


In [8]:
A = [[1, 1, 0, 1, 2], [2, 1, -1, 1, 1], [4, -1, -2, 2, 0], [3, -1, -1, 2, -3]]
x = eliminacion_gaussiana(A)
x

ValueError: No existe solución única.

Cuarto Literal

In [9]:
def eliminacion_gaussiana(A: np.ndarray) -> np.ndarray:
    A = np.array(A)

    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    for i in range(0, n - 1):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            print(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # --- Sustitución hacia atrás
    solucion = np.zeros(n, dtype=np.float32)
    solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = (A[i, n] - suma) / A[i, i]

    return solucion


a) 1/4X1 + 1/5X2 + 1/6X3 = 9\
1/3X1 + 1/4X2 + 1/5X3 = 8\
1/2X1 + X2 + 2X3 = 8


In [10]:
A = np.array([[1/4, 1/5, 1/6, 9], [1/3, 1/4, 1/5, 8], [1/2, 1, 2, 8]], dtype=np.float32)
solucion = eliminacion_gaussiana(A)
solucion

array([-227.07666,  476.92264, -177.69217], dtype=float32)

b) 3.333X1 + 15920X2 – 10.333X3 = 15913\
2.222X1 + 16.71X2 + 9.612X3 = 28.544\
1.5611X1 + 5.1791X2 + 1.6852X3 = 8.4254


In [11]:
A = np.array([[3.333, 15920, 10.333, 15913], [2.222, 16.71, 9.612, 28.544], [1.5611, 5.1791, 1.6852, 8.4254]], dtype=np.float32)
solucion = eliminacion_gaussiana(A)
solucion

Intercambiando filas 0 y 2


array([1.0024954, 0.9987004, 1.0016824], dtype=float32)

c) X1 + 1/2X2 + 1/3X3 + 1/4X4 = 1/6\
1/2X1 + 1/3X2 + 1/4X3 + 1/5X4 = 1/7\
1/3X1 + 1/4X2 + 1/5X3 + 1/6X4 = 1/8\
1/4X1 + 1/5X2 + 1/6X3 + 1/7X4 = 1/9


In [12]:
A = np.array([[1, 1/2, 1/3, 1/4, 1/6], [1/2, 1/3, 1/4, 1/5, 1/7], [1/3, 1/4, 1/5, 1/6, 1/8], [1/4, 1/5, 1/6, 1/7, 1/9]], dtype=np.float32)
solucion = eliminacion_gaussiana(A)
solucion

Intercambiando filas 0 y 3
Intercambiando filas 1 y 2


array([-0.03174073,  0.5951853 , -2.3808312 ,  2.7777011 ], dtype=float32)

d) 2X1 + X2 – X3 + X4 – 3X5 = 7\
X1 + 2X3 – X4 + X5 = 2\
-2X2 – X3 + X4 – X5 = -5\
3X1 + X2 – 4X3 + 5X5 = 6\
X1 – X2 – X3 – X4 + X5 = -3


In [13]:
A = np.array([[2, 1, -1, 1, -3, 7], [1, 0, 2, -1, 1, 2], [0, -2, -1, 1, -1, -5], [3, 1, -4, 0, 5, 6],[1, -1, -1, -1, 1, -3]], dtype=np.float32)
solucion = eliminacion_gaussiana(A)
solucion


Intercambiando filas 0 y 1
Intercambiando filas 2 y 3
Intercambiando filas 3 y 4


array([1.883041  , 2.8070176 , 0.73099416, 1.4385966 , 0.09356727],
      dtype=float32)

Quinto Literal

X1 – X2 + 𝛼 x3 = -2\
-X1 + 2X2 – 𝛼 x3 = 3\
𝛼 x1 + X2 + X3 = 2


a) Encuentre el valor(es) de 𝛼 para los que el sistema no tiene soluciones.

Se calculo el determinante de la matriz para igualarlo a cero y obtener los\ valores de alpha paraque no exista solucion en el sistema de ecuaciones.\
det(A) = (2 + a) + (-1 + a) + a(-1 - 2a) = 0\
det(A) = 2a^2 - a + 1 = 0\
a1 = 1\
a2 = -1/2\
No existe solución para [-1/2, 1]

b. Encuentre el valor(es) de 𝛼 para los que el sistema tiene un número infinito de soluciones.

Se transformo la matriz en una matriz triangular superior para asi escoger la\ ultima fila y encontrar el valor de alpha donde toda la fila tenga ceros y por\ ende se tenga infinitas soluciones\

1 - a^2 = 0\
Para los valores de [-1, 1] se tienen infinitas soluciones

c) Suponga que existe una única solución para una a determinada, encuentre la solución.

Asumimos el valor de alpha igual a 3

In [14]:
A = [[1, -1, 3], [-1, 2, -3], [3, 1, 1]]
b = [-2, 3, 2]
x = np.linalg.solve(A, b)
x


array([ 0.5,  1. , -0.5])

Ejercicios Aplicados

Sexto Literal

a)

In [15]:
A = [[1, 2, 0, 3], [1, 0, 2, 2], [0, 0, 1, 1]]
x = [1000, 500, 350, 400]
x = np.matmul(A, x)
print(x)


[3200 2500  750]


b)

In [16]:
A = [[1, 2, 0, 3], [1, 0, 2, 2], [0, 0, 1, 1]]
b = [3500, 2700, 900]
x = np.linalg.solve(A, b)
print(x)

LinAlgError: Last 2 dimensions of the array must be square

Creí que era de esta manera, pero no. Lo hice de manera analítica, que como resultado, la especie 1 puede llegar hasta 1800 integrantes. La especie 2, 3 y 4 dependen de ellas mismas. No se puede determinar de forma exacta ya que hay muchas distribuciones posibles

c)

In [17]:

A = [[2, 0, 3], [0, 2, 2], [0, 1, 1]]
b = [3500, 2700, 900]
x = np.linalg.solve(A, b)
print(x)

LinAlgError: Singular matrix

d)

In [18]:

A = [[1, 0, 3], [1, 2, 2], [0, 1, 1]]
b = [3500, 2700, 900]
x = np.linalg.solve(A, b)
print(x)


[900.          33.33333333 866.66666667]


Especie 1: 900, especie 2: 33, especie 3: 866

Ejercicios Teoricos

7. Repita el ejercicio 4 con el método Gauss – Jordan.

In [26]:
import numpy as np

def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.

    ## Parameters

    ``A``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    A = np.array(A, dtype=float)  # convertir en float, porque si no, convierte en enteros
    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]
    n_adds = 0
    n_mults = 0
    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            logging.info(f"\n{A}")
            raise ValueError("No existe solución única.")

        if p != i:
            print(f"Intercambiando filas {i} y {p}.")
            # swap rows
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]
            n_mults += 1 + (n + 1 - i - 1)
            n_adds += n + 1 - i - 1

        print(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        # Sin embargo, esto solo se accede al finalizar la matriz... Con todos los pivotes
        if A[n - 1, n] == 0:
            raise ValueError("Infinitas soluciones.")
        else:
            raise ValueError("Sin solución.")

    # --- Sustitución hacia atrás
    solucion = np.zeros(n)
    for i in range(n):
        solucion[i] = A[i, n] / A[i, i]
        n_mults += 1

    return solucion, n_adds, n_mults

a)

In [24]:
A = np.array([[1/4, 1/5, 1/6, 9], [1/3, 1/4, 1/5, 8], [1/2, 1, 2, 8]], dtype=np.float32)
solucion = gauss_jordan(A)
solucion


[[  0.25         0.2          0.16666667   9.        ]
 [  0.          -0.01666668  -0.02222223  -4.00000036]
 [  0.           0.59999999   1.66666666 -10.        ]]

[[ 2.50000000e-01  0.00000000e+00 -9.99999315e-02 -3.89999707e+01]
 [ 0.00000000e+00 -1.66666786e-02 -2.22222325e-02 -4.00000036e+00]
 [ 0.00000000e+00  0.00000000e+00  8.66666867e-01 -1.53999908e+02]]

[[ 2.50000000e-01  0.00000000e+00  0.00000000e+00 -5.67691746e+01]
 [ 0.00000000e+00 -1.66666786e-02  0.00000000e+00 -7.94871687e+00]
 [ 0.00000000e+00  0.00000000e+00  8.66666867e-01 -1.53999908e+02]]


(array([-227.07669834,  476.92267099, -177.69216091]), 12, 21)

b)

In [27]:
A = np.array([[3.333, 15920, 10.333, 15913], [2.222, 16.71, 9.612, 28.544], [1.5611, 5.1791, 1.6852, 8.4254]], dtype=np.float32)
solucion = gauss_jordan(A)
solucion

Intercambiando filas 0 y 2.

[[1.56110001e+00 5.17910004e+00 1.68519998e+00 8.42539978e+00]
 [0.00000000e+00 9.33829988e+00 7.21336224e+00 1.65516636e+01]
 [0.00000000e+00 1.59089425e+04 6.73504271e+00 1.58950115e+04]]

[[ 1.56110001e+00  0.00000000e+00 -2.31539169e+00 -7.54292769e-01]
 [ 0.00000000e+00  9.33829988e+00  7.21336224e+00  1.65516636e+01]
 [ 0.00000000e+00  0.00000000e+00 -1.22821148e+04 -1.23027834e+04]]

[[ 1.56110001e+00  0.00000000e+00  0.00000000e+00  1.56499531e+00]
 [ 0.00000000e+00  9.33829988e+00  0.00000000e+00  9.32616261e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.22821148e+04 -1.23027834e+04]]


(array([1.00249523, 0.99870027, 1.00168282]), 12, 21)

c)

In [28]:
A = np.array([[1, 1/2, 1/3, 1/4, 1/6], [1/2, 1/3, 1/4, 1/5, 1/7], [1/3, 1/4, 1/5, 1/6, 1/8], [1/4, 1/5, 1/6, 1/7, 1/9]], dtype=np.float32)
solucion = gauss_jordan(A)
solucion

Intercambiando filas 0 y 3.

[[ 0.25        0.2         0.16666667  0.14285715  0.11111111]
 [ 0.         -0.06666666 -0.08333334 -0.0857143  -0.07936507]
 [ 0.         -0.01666668 -0.02222223 -0.02380953 -0.02314815]
 [ 0.         -0.30000001 -0.33333334 -0.3214286  -0.27777778]]
Intercambiando filas 1 y 2.

[[ 0.25        0.         -0.09999993 -0.14285705 -0.16666654]
 [ 0.         -0.01666668 -0.02222223 -0.02380953 -0.02314815]
 [ 0.          0.          0.00555552  0.00952376  0.01322747]
 [ 0.          0.          0.06666657  0.10714271  0.13888871]]

[[ 0.25        0.          0.          0.02857173  0.07142935]
 [ 0.         -0.01666668  0.          0.01428579  0.0297621 ]
 [ 0.          0.          0.00555552  0.00952376  0.01322747]
 [ 0.          0.          0.         -0.00714306 -0.01984176]]

[[ 0.25        0.          0.          0.         -0.0079363 ]
 [ 0.         -0.01666668  0.          0.         -0.00992052]
 [ 0.          0.          0.00555552  0.         -0.01

(array([-0.03174521,  0.59523101, -2.38093701,  2.77776827]), 30, 46)

d)

In [29]:
A = np.array([[2, 1, -1, 1, -3, 7], [1, 0, 2, -1, 1, 2], [0, -2, -1, 1, -1, -5], [3, 1, -4, 0, 5, 6],[1, -1, -1, -1, 1, -3]], dtype=np.float32)
solucion = gauss_jordan(A)
solucion


Intercambiando filas 0 y 1.

[[  1.   0.   2.  -1.   1.   2.]
 [  0.   1.  -5.   3.  -5.   3.]
 [  0.  -2.  -1.   1.  -1.  -5.]
 [  0.   1. -10.   3.   2.   0.]
 [  0.  -1.  -3.   0.   0.  -5.]]

[[  1.   0.   2.  -1.   1.   2.]
 [  0.   1.  -5.   3.  -5.   3.]
 [  0.   0. -11.   7. -11.   1.]
 [  0.   0.  -5.   0.   7.  -3.]
 [  0.   0.  -8.   3.  -5.  -2.]]
Intercambiando filas 2 y 3.

[[  1.    0.    0.   -1.    3.8   0.8]
 [  0.    1.    0.    3.  -12.    6. ]
 [  0.    0.   -5.    0.    7.   -3. ]
 [  0.    0.    0.    7.  -26.4   7.6]
 [  0.    0.    0.    3.  -16.2   2.8]]
Intercambiando filas 3 y 4.

[[  1.           0.           0.           0.          -1.6
    1.73333333]
 [  0.           1.           0.           0.           4.2
    3.2       ]
 [  0.           0.          -5.           0.           7.
   -3.        ]
 [  0.           0.           0.           3.         -16.2
    2.8       ]
 [  0.           0.           0.           0.          11.4
    1.06666667]]

[[ 

(array([1.88304094, 2.80701754, 0.73099415, 1.43859649, 0.09356725]), 60, 85)